version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"    # Important: In a production environment your should remove the external port

  ecommerce.data:
    ports:
      - "6379:6379"    # Important: In a production environment your should remove the external port

  rabbitmq:
    ports:
      - "15672:15672"  # Important: In a production environment your should remove the external port
      - "5672:5672"    # Important: In a production environment your should remove the external port

  carrinho.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://10.0.75.1:5105
      - ConnectionString=ecommerce.data:6379
      # - IdentityUrl=http://identity.api
    ports:
      - "5103:80"

  catalogo.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_URLS=http://0.0.0.0:80
      # - ASPNETCORE_HTTPS_PORT=44375

    ports:
      - "50518:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      # - ASPNETCORE_HTTPS_PORT=44338
      - CallBackUrl=http://localhost:5100/
      # - MvcClient=http://${CASADOCODIGO_EXTERNAL_DNS_NAME_OR_IP}:5100              #Local: You need to open your local dev-machine firewall at range 5100-5110. 
    ports:
      - "5105:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  ordemdecompra.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      # - ASPNETCORE_HTTPS_PORT=44398
      # - ConnectionString=${CASADOCODIGO_ORDERING_DB:-sql.data}
      - ConnectionString=${CASADOCODIGO_ORDERING_DB:-Server=sql.data;Database=Microsoft.eShopOnContainers.Services.OrderingDb;User Id=sa;Password=Pass@word}
    ports:
      - "50516:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionString=${CASADOCODIGO_REDIS_BASKET_DB:-ecommerce.data}
      - CatalogoUrl=http://catalogo.api/
      # - IdentityUrl=http://127.0.0.1:50519/
      - IdentityUrl=http://10.0.75.1:5105/
      - ApiUrl=https://localhost:44359/
      - ApiUrlHC=https://localhost:44359/hc
      - CarrinhoUrl=http://carrinho.api/
      - OrdemDeCompraUrl=http://ordemdecompra.api/
      - CallBackUrl=http://localhost:5100/
      - SignalRServerUrl=http://mvc/
    ports:
      - "5100:80"

